name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [ push ]
jobs:
  s:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4.4.1
        env:
          JF_URL: https://tomjfrog.jfrog.io
        with:
          oidc-audience: github-jfrog-oidc




